#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Contatos")]
	public partial class ContatosModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertContato(Contato instance);
    partial void UpdateContato(Contato instance);
    partial void DeleteContato(Contato instance);
    #endregion
		
		public ContatosModelDataContext() : 
				base(global::Contatos.Properties.Settings.Default.ContatosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ContatosModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContatosModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContatosModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContatosModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Contato> Contatos
		{
			get
			{
				return this.GetTable<Contato>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contato")]
	public partial class Contato : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ContatoId;
		
		private string _ContatoNome;
		
		private string _ContatoCelular;
		
		private string _ContatoEmail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnContatoIdChanging(int value);
    partial void OnContatoIdChanged();
    partial void OnContatoNomeChanging(string value);
    partial void OnContatoNomeChanged();
    partial void OnContatoCelularChanging(string value);
    partial void OnContatoCelularChanged();
    partial void OnContatoEmailChanging(string value);
    partial void OnContatoEmailChanged();
    #endregion
		
		public Contato()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContatoId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ContatoId
		{
			get
			{
				return this._ContatoId;
			}
			set
			{
				if ((this._ContatoId != value))
				{
					this.OnContatoIdChanging(value);
					this.SendPropertyChanging();
					this._ContatoId = value;
					this.SendPropertyChanged("ContatoId");
					this.OnContatoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContatoNome", DbType="NVarChar(50)")]
		public string ContatoNome
		{
			get
			{
				return this._ContatoNome;
			}
			set
			{
				if ((this._ContatoNome != value))
				{
					this.OnContatoNomeChanging(value);
					this.SendPropertyChanging();
					this._ContatoNome = value;
					this.SendPropertyChanged("ContatoNome");
					this.OnContatoNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContatoCelular", DbType="NVarChar(15)")]
		public string ContatoCelular
		{
			get
			{
				return this._ContatoCelular;
			}
			set
			{
				if ((this._ContatoCelular != value))
				{
					this.OnContatoCelularChanging(value);
					this.SendPropertyChanging();
					this._ContatoCelular = value;
					this.SendPropertyChanged("ContatoCelular");
					this.OnContatoCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContatoEmail", DbType="NVarChar(50)")]
		public string ContatoEmail
		{
			get
			{
				return this._ContatoEmail;
			}
			set
			{
				if ((this._ContatoEmail != value))
				{
					this.OnContatoEmailChanging(value);
					this.SendPropertyChanging();
					this._ContatoEmail = value;
					this.SendPropertyChanged("ContatoEmail");
					this.OnContatoEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
